/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaapp;
import java.io.File;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void printFieldValue(String filePath) {
        try {
            // Load the XML file
            File xmlFile = new File(filePath);
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
            doc.getDocumentElement().normalize();

            // Get the list of record elements
            NodeList recordList = doc.getElementsByTagName("record");

            // Loop through each record element
            for (int i = 0; i < recordList.getLength(); i++) {
                Node recordNode = recordList.item(i);
                if (recordNode.getNodeType() == Node.ELEMENT_NODE) {
                    Element recordElement = (Element) recordNode;
                    System.out.println("Record " + (i + 1) + ":");
                    System.out.println("Name: " + recordElement.getElementsByTagName("name").item(0).getTextContent());
                    System.out.println("Postal Zip: " + recordElement.getElementsByTagName("postalZip").item(0).getTextContent());
                    System.out.println("Region: " + recordElement.getElementsByTagName("region").item(0).getTextContent());
                    System.out.println("Country: " + recordElement.getElementsByTagName("country").item(0).getTextContent());
                    System.out.println("Address: " + recordElement.getElementsByTagName("address").item(0).getTextContent());
                    System.out.println("List: " + recordElement.getElementsByTagName("list").item(0).getTextContent());
                    System.out.println();
                }
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new App().printFieldValue("C:/Users/g20g3211/SDP/data.xml");
    }

}