/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaapp;
import java.util.*;

import java.io.File;
import java.io.IOException;
import javax.xml.parsers.*;
//import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //reading the file and printing out the field values, number 1 of task 2
    public static void UserFieldValue() {
        try {
            // Load the XML file
            File xmlFile = new File("C:/Users/g20g3211/SDP/task2/app/src/main/java/javaapp/data.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
            doc.getDocumentElement().normalize();

            // Get the list of record elements
            NodeList recordList = doc.getElementsByTagName("record");

            // Loop through each record element
            for (int i = 0; i < recordList.getLength(); i++) {
                Node recordNode = recordList.item(i);
                if (recordNode.getNodeType() == Node.ELEMENT_NODE) {
                    Element recordElement = (Element) recordNode;
                    System.out.println("Record " + (i + 1) + ":");
                    System.out.println("Name: " + recordElement.getElementsByTagName("name").item(0).getTextContent());
                    System.out.println("Postal Zip: " + recordElement.getElementsByTagName("postalZip").item(0).getTextContent());
                    System.out.println("Region: " + recordElement.getElementsByTagName("region").item(0).getTextContent());
                    System.out.println("Country: " + recordElement.getElementsByTagName("country").item(0).getTextContent());
                    System.out.println("Address: " + recordElement.getElementsByTagName("address").item(0).getTextContent());
                    System.out.println("List: " + recordElement.getElementsByTagName("list").item(0).getTextContent());
                    System.out.println();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    //output only the user-selected fields from the file



    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //String fieldName = 
        new App().UserFieldValue();
    }

}